FROM node:14.18-alpine3.12 AS build-stage

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install --production --silent && mv node_modules ../

COPY . .

RUN chown -R node /usr/src/app

RUN chown -R node:node /usr/local

RUN npm run build

RUN npm i -g serve

EXPOSE 3000

USER node

CMD ["serve", "build"]
