FROM node:14.18-alpine3.12 AS build-stage

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm ci

COPY ["./src","./src"]

COPY ["./public","./public"]

COPY [".env",".env"]

EXPOSE 3000

CMD ["npm", "start"]


