services:
  proxy:
    image: nginx:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 80:80
    container_name: reversed-proxy-compose
    volumes:
      - ./reversed-proxy/nginx.conf:/etc/nginx/nginx.conf:ro   

  frontend:
    image: bamboo-frontend-react:compose
    build:
      context: ./frontend 		# The context will pick this directory as the "build context"
      dockerfile: Dockerfile.react 	# This will simply tell which dockerfile to read
    ports:
      - 3000:3000
    container_name: frontend-compose	# This will name the container hello-front-dev

  main-server:
    image: bamboo-main-server-compose:compose
    build:
      context: ./main-server
      dockerfile: Dockerfile.compose
    ports:
      - 5050:5050
    container_name: main-server-compose

  stock-api:
    image: bamboo-stock-api-compose:compose
    build: 
      context: ./stock-api
      dockerfile: Dockerfile.compose
    ports:
      - 5051:5051
    container_name: stock-api-compose
