

### Polygon tikers endpoint
GET https://api.polygon.io/v3/reference/tickers?exchange=XNYS&active=true&sort=ticker&order=asc&limit=10&apiKey=z0WumBiwbxcFPEDsiqcqA8XsPOSwdB97

### Polygon tickers endpoint with cursor, 
### the cursor comes with the 'next_url' property of the previous response
GET https://api.polygon.io/v3/reference/tickers?apiKey=z0WumBiwbxcFPEDsiqcqA8XsPOSwdB97&cursor=YWN0aXZlPXRydWUmZGF0ZT0yMDIxLTEwLTE5JmV4Y2hhbmdlPVhOWVMmbGltaXQ9MTAwMCZvcmRlcj1hc2MmcGFnZV9tYXJrZXI9RE9DUyU3QzI5YTZmMjBkMjI5NWZhYTk2Y2NlYzE0ZTMzYzlmYzRkOWQ3NDI5ZjBkNjJmNjRkYzhkNjk5YzFmZjFlYjM2ODQmc29ydD10aWNrZXI

### Ticker initialisation, get all tickers from polygon.io
GET http://localhost:6061/ticker/init

### get ticker by name, support fuzzy search
GET http://localhost:6061/ticker/name/AT&T

### get ticker by symbol, exactly matched, case-insensitive.
GET http://localhost:6061/ticker/symbol/T

### get ticker by id, return the exactly matched.
GET http://localhost:6061/ticker/id/6170d9d8913511aa4af87fb9

### get ticker by multi-factors query string, support fuzzy search
GET http://localhost:6061/ticker/search?ticker=f&primary_exchange=xnys



### get stock daily from polygon.io
GET https://api.polygon.io/v2/aggs/ticker/BABA/range/1/minute/2020-10-14/2020-10-14?adjusted=true&sort=asc&limit=5000&apiKey=z0WumBiwbxcFPEDsiqcqA8XsPOSwdB97

### get stock intraday data from alphavantage.co
GET https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=60min&apikey=HIS8F8CUE8LR8N9N


### get ticker's daily history data from alphavantage.co
GET https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey=HISHIS8F8CUE8LR8N9N




### test route
GET http://localhost:6061/ticker/aggs/APPL/minute/1/2020-10-10/2020-10-14

###multi/1/start/2020-10-10/end/2020-10-14

### ticker current 
GET http://localhost:6061/ticker/current/T


### sync aggregates from alphaVantages.co
GET http://localhost:6061/aggregate/sync/GM


### get aggregate by symbol and interval locally 
GET http://localhost:6061/aggregate/T/15min


### daily
GET https://www.alphavantage.co/query?apikey=HISHIS8F8CUE8LR8N9N&function=TIME_SERIES_DAILY&symbol=IBM&outputsize=compact

### intraday
GET https://www.alphavantage.co/query?apikey=HISHIS8F8CUE8LR8N9N&function=TIME_SERIES_INTRADAY&symbol=IBM&outputsize=compact&interval=15min


