FROM node:14.18-alpine3.12

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install --production --silent && mv node_modules ../

COPY ["./src", "./src"]

COPY [".env.compose", ".env"]

EXPOSE 5051

RUN chown -R node /usr/src/app

USER node

CMD ["npm", "start"]

