FROM node:16-alpine

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install --production --silent && mv node_modules ../

COPY ["./src", "./src"]

COPY ["./public", "./public"]

COPY ["./bin", "./bin"]

COPY ["../../bamboo.conf/.env.https.main-server", ".env"]

EXPOSE 5050

RUN chown -R node /usr/src/app

USER node

CMD ["npm", "start"]
